apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend  # Correct indentation for the selector
  ports:
  - port: 5001        # Port exposed by the service
    targetPort: 5001   # Port on the backend container
  type: NodePort