apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chat-app
spec:
  selector:
    app: frontend  # Correct indentation for the selector
  ports:
  - port: 80     # Port exposed by the service
    targetPort: 80
  type: NodePort   # Port on the backend container
