apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: chat-app
spec:
  capacity:
    storage: 1Gi  # Specify the storage size
  accessModes:
    - ReadWriteOnce  # Define the access mode
  storageClassName: "mongodb-storage"
  hostPath:
    path: /data # Specify the path on the host machine
