apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:  # Fixed typo (should be "selector" instead of "selectors")
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: chatapp-mongodb
        image: mongo:latest  # Fixed "images" to "image"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD  # Fixed typo (PASSWARD -> PASSWORD)
          value: secret
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db  # MongoDB's default data directory
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc  # Link to the PVC