version: '3.8'

services:
  frontend:
    image: unnati05/chatapp-frontend:latest
    ports:
      - "32571:80"
    depends_on:
      - backend
    networks:
      - chat-network
    environment:
      - BACKEND_URL=http://backend:5001

  backend:
    image: unnati05/chatapp-backend:latest
    ports:
      - "31378:5001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI="mongodb://root:root@mongodb:27017/dbname?authSource=admin"
      - PORT=5001
      - NODE_ENV=production
      - JWT_SECRET="eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTczNzg4MTE0NiwiaWF0IjoxNzM3ODgxMTQ2fQ.utc38TKfxbOlFM5Ql1XgZMTedskCAZDBZjE6fAVu-vw"
    networks:
      - chat-network

  mongo:
    image: mongo:latest
    ports:
      - "31053:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  mongodb_data:
  
