pipeline {
  agent any

  stages {
    stage('Fetch Changes') {
      steps {
        git branch: 'main',
          url: 'https://github.com/Unnati18-uk/chatty-3tier.git'
      }
    }
    stage('Code Quality') {
      steps {
        sh '''/opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=3tier-demo \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://3.26.102.0:9000 \
          -Dsonar.login=f3251b92df185001d75c1db2d14be8316e6a0b99'''
      }
    }
    stage('Test') {
      steps {
        // Add your test commands here
        echo "Running tests..."
      }
    }
    stage('Deploy') {
      steps {
        script {
          // Only deploy if the previous stages were successful
         sh 'docker compose -f project/full-stack_chatApp/docker-compose.yml up -d --build'
        }
      }
    }
  }
}

